name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel_build:
    name: Laravel Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Copy file example env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Create File Database
        run: touch database/database.sqlite

      - name: Run Migration Database
        run: php artisan migrate:fresh --seed

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Node.JS
        run: npm run build

  laravel_test:
    name: Laravel Test
    runs-on: ubuntu-latest
    needs: laravel_build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Copy file example env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Create File Database
        run: touch database/database.sqlite

      - name: Run Migration Database
        run: php artisan migrate:fresh --seed

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Node.JS
        run: npm run build

      - name: Run tests
        run: ./vendor/bin/phpunit

  notification:
    name: Notification
    runs-on: ubuntu-latest
    needs: [laravel_build, laravel_test]
    if: always() # Ensure this job runs even if previous jobs fail

    steps:
      - name: Check Laravel Build status
        if: ${{ needs.laravel_build.result == 'success' }}
        run: echo "Laravel Build job succeeded"

      - name: Check Laravel Test status
        if: ${{ needs.laravel_test.result == 'success' }}
        run: echo "Laravel Test job succeeded"

      - name: Check Laravel Build status
        if: ${{ needs.laravel_build.result == 'failure' }}
        run: echo "Laravel Build job failed"

      - name: Check Laravel Test status
        if: ${{ needs.laravel_test.result == 'failure' }}
        run: echo "Laravel Test job failed"
