name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel_build:
    name: Laravel Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Steps untuk setup PHP, install dependencies, generate key, dll

  laravel_test:
    name: Laravel Test
    runs-on: ubuntu-latest
    needs: laravel_build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Steps untuk setup PHP, install dependencies, generate key, dll

      - name: Run tests
        run: ./vendor/bin/phpunit

  laravel_notification:
    name: Laravel Notification
    runs-on: ubuntu-latest
    needs:
      - laravel_build
      - laravel_test
  
    steps:
      - name: Check previous job status
        if: always()  # Job akan selalu dijalankan, terlepas dari hasil job sebelumnya
        run: |
          if [ "${{ needs.laravel_build.result }}" == 'success' ] && [ "${{ needs.laravel_test.result }}" == 'success' ]; then
            echo "All previous jobs were successful."
          else
            echo "At least one previous job failed."
            exit 1
          fi
