name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel_build:
    name: Laravel Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust based on your project's PHP version

      - run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - run: cp .env.example .env

      - run: php artisan key:generate

      - run: touch database/database.sqlite

      - run: php artisan migrate:fresh --seed

      # - name: Install Breeze  # Uncomment if using Breeze (optional)
      #   run: php artisan breeze:install --no-interaction

      - uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust based on your project's Node.js version

      - run: npm install  # Or yarn install if using Yarn

      - run: npm run build

  laravel_test:
    name: Laravel Test
    runs-on: ubuntu-latest
    needs: laravel_build  # Ensure this job runs after laravel_build

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - run: cp .env.example .env

      - run: php artisan key:generate

      - run: touch database/database.sqlite

      - run: php artisan migrate:fresh --seed

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - run: npm install

      - run: npm run build

      - run: ./vendor/bin/phpunit

  notification:
    name: Notification
    runs-on: ubuntu-latest
    needs: [laravel_build, laravel_test]  # Wait for both build and test jobs

    steps:
      - uses: actions/checkout@v2

      - name: Check Job Statuses
        run: |
          build_job_status=${{ jobs.laravel_build.status }}
          test_job_status=${{ jobs.laravel_test.status }}

          if [[ $build_job_status == 'success' && $test_job_status == 'success' ]]; then
            echo "Sukses! Build dan testing berhasil."
          else
            echo "Gagal! Build atau testing mengalami kegagalan."
          fi
