name: Laravel CI with Slack Notifications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel_build:
    name: Laravel Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Copy file example env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Create File Database
        run: touch database/database.sqlite

      - name: Run Migration Database
        run: php artisan migrate:fresh --seed

      # - name: Install Breeze
      #   run: php artisan breeze:install --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install # Atau yarn install jika Anda menggunakan Yarn

      - name: Build Node.JS
        run: npm run build

  laravel_test:
    name: Laravel Test
    runs-on: ubuntu-latest
    needs: laravel_build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Copy file example env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Create File Database
        run: touch database/database.sqlite

      - name: Run Migration Database
        run: php artisan migrate:fresh --seed

      # - name: Install Breeze
      #   run: php artisan breeze:install --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install # Atau yarn install jika Anda menggunakan Yarn

      - name: Run tests
        run: ./vendor/bin/phpunit

  laravel_job_status:
    name: Report Job Status and Send Slack Notification
    runs-on: ubuntu-latest
    needs: [laravel_build, laravel_test]
    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]
    steps:
      - name: Get Job Statuses
        run: |
          build_status=$(curl ${{ github.action_url }}/workflows/${{ github.workflow }}/runs/${{ github.run_id }}/jobs/laravel_build/statuses)
          test_status=$(curl ${{ github.action_url }}/workflows/${{ github.workflow }}/runs/${{ github.run_id }}/jobs/laravel_test/statuses)

      - name: Determine Notification Message
        if: ${{ success() }}
        run: |
          if [[ $build_status == 'completed' && $test_status == 'completed' ]]; then
            notification_message="**Laravel Build and Tests Succeeded!**"
          else
            notification_message="**One or more jobs failed! See details in the workflow logs.**"
          fi
        env:
          NOTIFICATION_MESSAGE: ${{ steps.determine_notification_message.outputs.message }}

      - name: Send Slack Notification
        if: ${{ success() }}
        uses: slack/slack@v3
        with:
          # Slack API token
          token: ${{ secrets.SLACK_API_TOKEN }}
          # Slack channel or webhook URL
          channel: '#notifications'
          text: "Job Status: ${{ env.NOTIFICATION_MESSAGE }} - Job **${{ job.name }}** completed on **${{ github.workflow }}** workflow."
