name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel_build:
    name: Laravel Build
    runs-on: ubuntu-latest

    steps:
      # Steps for Laravel Build job

  laravel_test:
    name: Laravel Test
    runs-on: ubuntu-latest
    needs: laravel_build

    steps:
      # Steps for Laravel Test job

  notification:
    name: Notification
    runs-on: ubuntu-latest
    needs: [laravel_build, laravel_test]
    if: always() # Ensure this job runs even if previous jobs fail

    steps:
      - name: Check Laravel Build status
        if: ${{ needs.laravel_build.outputs.build_status == 'success' }}
        run: echo "Laravel Build job succeeded"

      - name: Check Laravel Test status
        if: ${{ needs.laravel_test.outputs.test_status == 'success' }}
        run: echo "Laravel Test job succeeded"

      - name: Check Laravel Build status
        if: ${{ needs.laravel_build.outputs.build_status == 'failure' }}
        run: echo "Laravel Build job failed"

      - name: Check Laravel Test status
        if: ${{ needs.laravel_test.outputs.test_status == 'failure' }}
        run: echo "Laravel Test job failed"
