name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel_build:
    name: Laravel Build
    runs-on: ubuntu-latest

    steps:
      # Steps for build job as before...

  laravel_test:
    name: Laravel Test
    runs-on: ubuntu-latest
    needs: laravel_build

    steps:
      # Steps for test job as before...

  notification:
    name: Notification
    runs-on: ubuntu-latest
    needs: [laravel_build, laravel_test]
    if: always()

    steps:
      - name: Notify on failure
        if: ${{ failure() }}
        uses: slack/webhook-action@v2
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: POST
          payload: '{"text": "One of the Laravel CI jobs failed!"}'

      - name: Notify on success
        if: ${{ success() }}
        uses: slack/webhook-action@v2
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: POST
          payload: '{"text": "All Laravel CI jobs passed successfully!"}'
